Repository eduardomv2/LUX-APP, pull requests merged in 2024-07, with the labels that each got.

#32 Cambios para saber como va la rama (botones de ajuste de ventana)
  TEST 3 LUX/FORMS/Principal.Designer.cs
Labels: bug

#33 Diseño para empezar a trabajar con lo siguiente
  TEST 3 LUX/FORMS/Principal.Designer.cs
  TEST 3 LUX/FORMS/Principal.cs
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/Properties/Resources.Designer.cs
  TEST 3 LUX/Properties/Resources.resx
  TEST 3 LUX/Resources/pencils-2782840_640.png
Labels: enhancement, help wanted

#34 Sigo viendo el diseño del Forms
  TEST 3 LUX/FORMS/Principal actividades.Designer.cs
  TEST 3 LUX/FORMS/Principal actividades.cs
  TEST 3 LUX/FORMS/Principal actividades.resx
  TEST 3 LUX/FORMS/Principal.Designer.cs
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/Properties/Resources.Designer.cs
  TEST 3 LUX/Properties/Resources.resx
  TEST 3 LUX/Resources/config.png
Labels: help wanted, invalid, question

#39 Cambio en la paleta de colores del forms MENU
  TEST 3 LUX/FORMS/Principal actividades.Designer.cs
  TEST 3 LUX/FORMS/Principal.Designer.cs
Labels: help wanted

#43 Ultimos cambios de comunicación
  TEST 3 LUX/FORMS/Comunicacion/ComunicacionPrincipal.Designer.cs
  TEST 3 LUX/FORMS/Comunicacion/ComunicacionPrincipal.cs
  TEST 3 LUX/FORMS/Comunicacion/ComunicacionPrincipal.resx
  TEST 3 LUX/FORMS/Comunicacion/Controles personalizados/RBotonAmarillo.cs
  TEST 3 LUX/FORMS/Comunicacion/Controles personalizados/RBotonRojo.cs
  TEST 3 LUX/FORMS/Comunicacion/Controles personalizados/RBotonVerde.cs
  TEST 3 LUX/FORMS/Principal.Designer.cs
  TEST 3 LUX/FORMS/Principal.cs
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/packages.config
Labels: enhancement

#50 Inclusion de nuevos sub-apartados para la seccion de "Comunicacion"
  TEST 3 LUX/FORMS/Comunicacion/ComunicacionPrincipal.Designer.cs
  TEST 3 LUX/FORMS/Comunicacion/ComunicacionPrincipal.cs
  TEST 3 LUX/FORMS/Comunicacion/ComunicacionPrincipal.resx
  TEST 3 LUX/FORMS/Comunicacion/Menus secundarios/ComunicacionPictogramas.Designer.cs
  TEST 3 LUX/FORMS/Comunicacion/Menus secundarios/ComunicacionPictogramas.cs
  TEST 3 LUX/FORMS/Comunicacion/Menus secundarios/ComunicacionPictogramas.resx
  TEST 3 LUX/FORMS/Comunicacion/Menus secundarios/ComunicacionTTS.Designer.cs
  TEST 3 LUX/FORMS/Comunicacion/Menus secundarios/ComunicacionTTS.cs
  TEST 3 LUX/FORMS/Comunicacion/Menus secundarios/ComunicacionTTS.resx
  TEST 3 LUX/LUX.csproj
Labels: documentation

#56 Avances en el apartado de Pictogramas actividad Bien o Mal
  TEST 3 LUX/Forms_Contenido/Actividades/DibujarActividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/DibujarActividades.cs
  TEST 3 LUX/Forms_Contenido/Actividades/DibujarActividades.resx
  TEST 3 LUX/Forms_Contenido/Actividades/Pictogramas_Actividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Pictogramas_Actividades.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Pictogramas_Actividades.resx
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Controles personalizados/RBotonAmarillo.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Controles personalizados/RBotonRojo.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Controles personalizados/RBotonVerde.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionPictogramas.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionPictogramas.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionPictogramas.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionTTS.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionTTS.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionTTS.resx
  TEST 3 LUX/Forms_Contenido/Principal/Principal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.resx
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/Pictogramas_BienMal.cs
  TEST 3 LUX/Properties/Resources.Designer.cs
  TEST 3 LUX/Properties/Resources.resx
  TEST 3 LUX/Resources/ACCIONES.png
  TEST 3 LUX/Resources/ACCIONES1.png
  TEST 3 LUX/Resources/Agregar un título (1)1.png
  TEST 3 LUX/Resources/Agregar un título (2)1.png
  TEST 3 LUX/Resources/Agregar un título (3)1.png
  TEST 3 LUX/Resources/Agregar un título (4).png
  TEST 3 LUX/Resources/Agregar un título1.png
  TEST 3 LUX/Resources/Axelbotones.png
  TEST 3 LUX/Resources/BotonBien.png
  TEST 3 LUX/Resources/BotonBien1.png
  TEST 3 LUX/Resources/Diseño sin título (61)1.png
  TEST 3 LUX/Resources/Diseño sin título (62)1.png
  TEST 3 LUX/Resources/Diseño sin título (63)1.png
  TEST 3 LUX/Resources/Diseño sin título (64)1.png
  TEST 3 LUX/Resources/Diseño sin título (65).png
  TEST 3 LUX/Resources/Diseño sin título (66).png
  TEST 3 LUX/Resources/accionmala.jpg
  TEST 3 LUX/Resources/accionmala1.jpg
Labels: enhancement, help wanted, invalid, question

#57 Rediseño ligero al apartado de "comunicación"
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionPictogramas.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionPictogramas.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionPictogramas.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionTTS.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionTTS.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionTTS.resx
Labels: documentation

#58 Rediseño ligero en el formulario main
  TEST 3 LUX/Forms_Contenido/Principal/Principal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.resx
  TEST 3 LUX/LUX.csproj
Labels: documentation

#60 Reajuste a la pantalla principal y paneles en actividades, solo para …
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.resx
Labels: wontfix

#62 Rediseño ligero en "ComunicaciónTTS"
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionTTS.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Menus secundarios/ComunicacionTTS.resx
Labels: documentation

#67 Apartado CalcarDibujar_Actividades avanzado
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Recursos_Actividades/GIF/Diseño sin título (3).gif
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar_Actividades/Calcar_Actividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar_Actividades/Calcar_Actividades.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar_Actividades/Calcar_Actividades.resx
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar_Actividades/DibujarActividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar_Actividades/DibujarActividades.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar_Actividades/DibujarEscritura_Actividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar_Actividades/DibujarEscritura_Actividades.resx
  TEST 3 LUX/Forms_Contenido/Principal/Principal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.resx
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/Properties/Resources.Designer.cs
  TEST 3 LUX/Properties/Resources.resx
  TEST 3 LUX/Resources/2.png
  TEST 3 LUX/Resources/Diseño sin título (81).png
  TEST 3 LUX/Resources/Diseño sin título (82).png
  TEST 3 LUX/Resources/Diseño sin título (83).png
  TEST 3 LUX/Resources/Diseño sin título (84).png
  TEST 3 LUX/Resources/Diseño sin título (86).png
Labels: enhancement, help wanted

#69 Cambios en el diseño de Dibujar
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar/Dibujar_Calcar/Calcar_Actividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar/Dibujar_Libre/DibujarActividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Dibujar/Dibujar_Libre/DibujarActividades.cs
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/Properties/Resources.Designer.cs
  TEST 3 LUX/Properties/Resources.resx
  TEST 3 LUX/Resources/Diseño sin título (96).png
  TEST 3 LUX/Resources/Diseño sin título (97).png
  TEST 3 LUX/Resources/Diseño sin título (98).png
  TEST 3 LUX/Resources/Diseño sin título (99).png
Labels: enhancement
