Repository eduardomv2/LUX-APP, pull requests merged in 2024-08, with the labels that each got.

#73 Optimización en el dibujado y animaciónes de entrada y salida
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Controles personalizados/DoubleBufferedFlowLayoutPanel.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/ComunicacionPictogramas.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/ComunicacionPictogramas.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/ComunicacionPictogramas.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/TTS/ComunicacionTTS.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/TTS/ComunicacionTTS.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/TTS/ComunicacionTTS.resx
  TEST 3 LUX/LUX.csproj
Labels: documentation

#75 Ajuste de boton
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/ComunicacionPictogramas.cs
Labels: documentation

#76 Optimización en la carga de formularios v2
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Controles personalizados/DoubleBufferedTableLayoutPanel.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/ComunicacionPictogramas.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/ComunicacionPictogramas.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/ComunicacionPictogramas.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/TTS/ComunicacionTTS.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/TTS/ComunicacionTTS.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/TTS/ComunicacionTTS.resx
  TEST 3 LUX/LUX.csproj
Labels: documentation

#84 Emociones listo
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Emociones.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Emociones.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Emociones.resx
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/Caerse_Triste.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/ComidaFavorita_Feliz.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/HeladoCaido_Triste.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/Jugar_Feliz.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/Niña_Sorprendido.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/Niño_Asustado.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/Niño_Enojado.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/Regalo_Feliz.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/SeBurlan_Enojado.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Acciones/TeRobanPaleta_Triste.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Emociones/1.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Emociones/2.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Emociones/4.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Emociones/Recursos/Emociones/FELIZ (4).png
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/Properties/Resources.Designer.cs
  TEST 3 LUX/Properties/Resources.resx
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-14T053456.294.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-14T053734.700.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-14T053819.767.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-14T053850.615.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-14T055056.180.png
  TEST 3 LUX/Resources/FELIZ (1).png
  TEST 3 LUX/Resources/FELIZ (2).png
  TEST 3 LUX/Resources/FELIZ (3).png
  TEST 3 LUX/Resources/FELIZ.png
Labels: enhancement

#85 Opcion correcta
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Opcion_Correcta.Designer.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Opcion_Correcta.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Opcion_Correcta.resx
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Animal_Cerdo.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Animal_Elefante.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Animal_Panda.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Animal_Perezoso.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Animal_Tiburon.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Comida_Fideos.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Comida_Hamburguesa.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Comida_Pollo.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Comida_Sandia.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Comida_Subway.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Objeto_Crayones.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Objeto_Lentes.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Objeto_Llave.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Objeto_Paraguas.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Objeto_Silla.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Persona_DosNiños.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Persona_Niña.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Persona_Niñaa.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Persona_Niño.png
  TEST 3 LUX/Forms_Contenido/Actividades/Secciones/Pictogramas/Opcion_Correcta/Recursos/Persona_Niñoo.png
  TEST 3 LUX/Forms_Contenido/Principal/Principal.cs
  TEST 3 LUX/Forms_Contenido/Principal/Resources/Fondos/Diseño sin título (81).png
  TEST 3 LUX/Forms_Contenido/Principal/Resources/Fondos/Diseño sin título (82).png
  TEST 3 LUX/Forms_Contenido/Principal/Resources/Fondos/Diseño sin título (83).png
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/Properties/Resources.Designer.cs
  TEST 3 LUX/Properties/Resources.resx
  TEST 3 LUX/Resources/Agregar un subtítulo (3).png
  TEST 3 LUX/Resources/Diseño sin título (2).jpg
  TEST 3 LUX/Resources/Diseño sin título (3).jpg
  TEST 3 LUX/Resources/Diseño sin título (4).jpg
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-15T034237.958.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-15T035014.528.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-15T052314.881.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-15T052453.337.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-15T052534.016.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-15T052707.487.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-15T053613.451.png
Labels: enhancement

#86 Fondos en form principal
  TEST 3 LUX/Forms_Contenido/Principal/Principal.cs
  TEST 3 LUX/Forms_Contenido/Principal/Resources/Fondos/Fondo_FloresBlancas.png
  TEST 3 LUX/Forms_Contenido/Principal/Resources/Fondos/Fondo_Montañas.png
  TEST 3 LUX/Forms_Contenido/Principal/Resources/Fondos/Fondo_Primaveral.png
  TEST 3 LUX/LUX.csproj
Labels: enhancement

#87 Se agregaron funciónes
  TEST 3 LUX/Forms_Contenido/Comunicacion/Controles personalizados/RBotonProp.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/Social/ComunicacionSocial.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/Social/ComunicacionSocial.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/Social/ComunicacionSocial.resx
Labels: documentation

#88 el cuerpo del boton rutina ya está
  TEST 3 LUX/ConfiguracionGlobal.cs
  TEST 3 LUX/Forms_Contenido/Actividades/Principal actividades.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.cs
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Cartas.Designer.cs
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Cartas.cs
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Cartas.resx
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Acomodar_la_caña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Acomodar_la_caño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Acostarme_a_dormir_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Acostarme_a_dormir_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Bañarme_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Bañarme_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Biblioteca.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Casa.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Cenar_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Cenar_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Cine.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Comer_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Comer_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Desayunar_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Desayunar_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Escuela.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Jugar_con_amigos_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Jugar_con_amigos_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Lavarme_los_dientes_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Lavarme_los_dientes_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Levantarme_de_la_cama_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Levantarme_de_la_cama_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Recoger_mis_juguetes_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Recoger_mis_juguetes_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Supermercado.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Vestirme_niña.png
  TEST 3 LUX/Forms_Contenido/Rutina/Cartas/Recursos/Vestirme_niño.png
  TEST 3 LUX/Forms_Contenido/Rutina/RutinaR/Recursos/Fondos/preliminar.png
  TEST 3 LUX/Forms_Contenido/Rutina/RutinaR/Recursos/Mañana1.gif
  TEST 3 LUX/Forms_Contenido/Rutina/RutinaR/Recursos/Noche.gif
  TEST 3 LUX/Forms_Contenido/Rutina/RutinaR/Recursos/Tarde1.gif
  TEST 3 LUX/Forms_Contenido/Rutina/RutinaR/Rutina.Designer.cs
  TEST 3 LUX/Forms_Contenido/Rutina/RutinaR/Rutina.cs
  TEST 3 LUX/Forms_Contenido/Rutina/RutinaR/Rutina.resx
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/Properties/Resources.Designer.cs
  TEST 3 LUX/Properties/Resources.resx
  TEST 3 LUX/Resources/600 AM - 1200 PM (1).png
  TEST 3 LUX/Resources/600 AM - 1200 PM (2).png
  TEST 3 LUX/Resources/600 AM - 1200 PM (3).png
  TEST 3 LUX/Resources/600 AM - 1200 PM (4).png
  TEST 3 LUX/Resources/600 AM - 1200 PM.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-17T020754.281.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-17T020754.2811.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-17T070732.861.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-17T070955.228.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-17T071219.878.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-17T071713.647.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-19T052451.118.png
  TEST 3 LUX/Resources/Diseño sin título - 2024-08-20T002129.778.png
  TEST 3 LUX/Resources/kilos.png
Labels: enhancement, help wanted

#90 gestion emocional base
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.resx
  TEST 3 LUX/Forms_Contenido/Gestion_emocional/Controles personalizados/RPictureBox.cs
  TEST 3 LUX/Forms_Contenido/Gestion_emocional/Gestion_emocional.Designer.cs
  TEST 3 LUX/Forms_Contenido/Gestion_emocional/Gestion_emocional.cs
  TEST 3 LUX/Forms_Contenido/Gestion_emocional/Gestion_emocional.resx
  TEST 3 LUX/LUX.csproj
  TEST 3 LUX/packages.config
Labels: documentation

#91 Se eliminaron botones
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/ComunicacionPrincipal.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/Social/ComunicacionSocial.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/Social/ComunicacionSocial.resx
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/Vocabulario/ComunicacionVocabulario.Designer.cs
  TEST 3 LUX/Forms_Contenido/Comunicacion/Secciones/Pictogramas/Vocabulario/ComunicacionVocabulario.resx
  TEST 3 LUX/Forms_Contenido/Gestion_emocional/Gestion_emocional.Designer.cs
  TEST 3 LUX/Forms_Contenido/Gestion_emocional/Gestion_emocional.cs
  TEST 3 LUX/Forms_Contenido/Gestion_emocional/Gestion_emocional.resx
  TEST 3 LUX/Forms_Contenido/Principal/Principal.Designer.cs
  TEST 3 LUX/Forms_Contenido/Principal/Principal.cs
Labels: documentation
